### ISSUE TITLE
Disable wrapping body elements

### ISSUE THREAD

**Issue by ridgeworks** [thomaspark/scoper#3]
scoper.js attempts to wrap <body> elements where the scoped style element is a direct descendant, which effectively eliminates the applicability of the style content. I think it's fairly safe to just leave these style elements as is since they apply to the whole body.

I know this is an unusual case with an obvious manual workaround, but I'm auto generating the html and I don't always know where the scoped styles are going to be placed in the document.

**Comment by thomaspark** [comment]
Thanks for the suggestion. Wrapping `body` with another element is definitely not desired, and leaving `style` as-is for this case is a good solution.

**Comment by ridgeworks** [comment]
Great. And thanks for a very useful polyfill.
