### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by xcatliu** [thomaspark/scoper#9]
The error `ReferenceError: document is not defined` shows when I tried to use it in the node environment.

Maybe we can add a null check before calling `document.createElement`?

**Comment by thomaspark** [comment]
Hi @xcatliu, good idea to add a check. So is your expected behavior to just return?

**Comment by xcatliu** [comment]
I guess in the node env, we just need the `scoper` function.

**Comment by thomaspark** [comment]
Can you try this one and see if it's what you need?

https://github.com/thomaspark/scoper/tree/issue9

**Comment by xcatliu** [comment]
Looks good, thanks!
